// ─────────────────────────────────────────────────────────────────────────────
// LEVEL-UP DATA  (2024 D&D rules)
// ─────────────────────────────────────────────────────────────────────────────

// Proficiency bonus by character level
export const PROF_BY_LEVEL = {
  1:2, 2:2, 3:2, 4:2, 5:3, 6:3, 7:3, 8:3,
  9:4, 10:4, 11:4, 12:4, 13:5, 14:5, 15:5, 16:5,
  17:6, 18:6, 19:6, 20:6,
}

// Hit-die average (used for HP on level up)
export const HIT_DIE_AVG = { d6:4, d8:5, d10:6, d12:7 }

// ── Full caster spell slot table (Bard, Cleric, Druid, Sorcerer, Wizard) ─────
// slots[level] = { 1:n, 2:n, ... }
const FULL_CASTER_SLOTS = {
  1:  { 1:2 },
  2:  { 1:3 },
  3:  { 1:4, 2:2 },
  4:  { 1:4, 2:3 },
  5:  { 1:4, 2:3, 3:2 },
  6:  { 1:4, 2:3, 3:3 },
  7:  { 1:4, 2:3, 3:3, 4:1 },
  8:  { 1:4, 2:3, 3:3, 4:2 },
  9:  { 1:4, 2:3, 3:3, 4:3, 5:1 },
  10: { 1:4, 2:3, 3:3, 4:3, 5:2 },
  11: { 1:4, 2:3, 3:3, 4:3, 5:2, 6:1 },
  12: { 1:4, 2:3, 3:3, 4:3, 5:2, 6:1 },
  13: { 1:4, 2:3, 3:3, 4:3, 5:2, 6:1, 7:1 },
  14: { 1:4, 2:3, 3:3, 4:3, 5:2, 6:1, 7:1 },
  15: { 1:4, 2:3, 3:3, 4:3, 5:2, 6:1, 7:1, 8:1 },
  16: { 1:4, 2:3, 3:3, 4:3, 5:2, 6:1, 7:1, 8:1 },
  17: { 1:4, 2:3, 3:3, 4:3, 5:2, 6:1, 7:1, 8:1, 9:1 },
  18: { 1:4, 2:3, 3:3, 4:3, 5:3, 6:1, 7:1, 8:1, 9:1 },
  19: { 1:4, 2:3, 3:3, 4:3, 5:3, 6:2, 7:1, 8:1, 9:1 },
  20: { 1:4, 2:3, 3:3, 4:3, 5:3, 6:2, 7:2, 8:1, 9:1 },
}

// Half caster (Paladin, Ranger) — slots start at level 1 (2024)
const HALF_CASTER_SLOTS = {
  1:  { 1:2 },
  2:  { 1:2 },
  3:  { 1:3 },
  4:  { 1:3 },
  5:  { 1:4, 2:2 },
  6:  { 1:4, 2:2 },
  7:  { 1:4, 2:3 },
  8:  { 1:4, 2:3 },
  9:  { 1:4, 2:3, 3:2 },
  10: { 1:4, 2:3, 3:2 },
  11: { 1:4, 2:3, 3:3 },
  12: { 1:4, 2:3, 3:3 },
  13: { 1:4, 2:3, 3:3, 4:1 },
  14: { 1:4, 2:3, 3:3, 4:1 },
  15: { 1:4, 2:3, 3:3, 4:2 },
  16: { 1:4, 2:3, 3:3, 4:2 },
  17: { 1:4, 2:3, 3:3, 4:3, 5:1 },
  18: { 1:4, 2:3, 3:3, 4:3, 5:1 },
  19: { 1:4, 2:3, 3:3, 4:3, 5:2 },
  20: { 1:4, 2:3, 3:3, 4:3, 5:2 },
}

// Warlock Pact Magic
const WARLOCK_SLOTS = {
  1:  { 1:1 },
  2:  { 1:2 },
  3:  { 2:2 },
  4:  { 2:2 },
  5:  { 3:2 },
  6:  { 3:2 },
  7:  { 4:2 },
  8:  { 4:2 },
  9:  { 5:2 },
  10: { 5:2 },
  11: { 5:3 },
  12: { 5:3 },
  13: { 5:3 },
  14: { 5:3 },
  15: { 5:3 },
  16: { 5:3 },
  17: { 5:4 },
  18: { 5:4 },
  19: { 5:4 },
  20: { 5:4 },
}

export const SPELL_SLOTS_BY_CLASS_LEVEL = {
  Bard:     FULL_CASTER_SLOTS,
  Cleric:   FULL_CASTER_SLOTS,
  Druid:    FULL_CASTER_SLOTS,
  Sorcerer: FULL_CASTER_SLOTS,
  Wizard:   FULL_CASTER_SLOTS,
  Paladin:  HALF_CASTER_SLOTS,
  Ranger:   HALF_CASTER_SLOTS,
  Warlock:  WARLOCK_SLOTS,
}

// ── Cantrips by class & level ─────────────────────────────────────────────────
export const CANTRIPS_BY_CLASS_LEVEL = {
  Bard:     { 1:2, 4:3, 10:4 },
  Cleric:   { 1:3, 4:4, 10:5 },
  Druid:    { 1:2, 4:3, 10:4 },
  Sorcerer: { 1:4, 4:5, 10:6 },
  Wizard:   { 1:3, 4:4, 10:5 },
  Warlock:  { 1:2, 4:3, 10:4 },
}

// ── All class features by level ───────────────────────────────────────────────
// choices: array of { type, label, options[] } — these trigger the LevelUpPage
export const CLASS_LEVEL_FEATURES = {

  // ── Barbarian ──────────────────────────────────────────────────────────────
  Barbarian: {
    2:  { features: [{ name: 'Danger Sense', description: 'You have advantage on Dexterity saving throws against effects you can see, such as traps and spells, as long as you are not blinded, deafened, or incapacitated.' },
                     { name: 'Reckless Attack', description: 'When you make your first attack on your turn, you can decide to attack recklessly, giving you advantage on melee weapon attacks using Strength this turn but attack rolls against you have advantage until your next turn.' }] },
    3:  { features: [{ name: 'Primal Knowledge', description: 'You gain proficiency in one skill of your choice from the Barbarian skill list.' }],
          choices: [{ type: 'subclass', label: 'Primal Path', options: ['Path of the Berserker','Path of the Totem Warrior','Path of the Wild Heart','Path of the World Tree','Path of the Zealot'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Extra Attack', description: 'You can attack twice instead of once when you take the Attack action on your turn.' },
                     { name: 'Fast Movement', description: 'Your speed increases by 10 feet while you are not wearing heavy armor.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Primal Path subclass.' }] },
    7:  { features: [{ name: 'Feral Instinct', description: 'Your instincts are so honed that you have advantage on Initiative rolls. Additionally, if you are surprised at the beginning of combat, you can act normally on your first turn if you enter your Rage before doing anything else.' },
                     { name: 'Instinctive Pounce', description: 'As part of the Bonus Action you take to enter your Rage, you can move up to half your speed.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Brutal Strike', description: 'If you use Reckless Attack, you can forgo advantage on one attack roll to deal an extra 1d10 damage on a hit.' }] },
    10: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Primal Path subclass.' }] },
    11: { features: [{ name: 'Relentless Rage', description: 'If you drop to 0 hit points while you\'re raging and don\'t die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead. Each time you use this feature, the DC increases by 5.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    13: { features: [{ name: 'Brutal Strike improvement', description: 'Your Brutal Strike extra damage increases to 2d10.' }] },
    14: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Primal Path subclass.' }] },
    15: { features: [{ name: 'Persistent Rage', description: 'Your Rage is so fierce it ends early only if you fall unconscious or you choose to end it.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    17: { features: [{ name: 'Brutal Strike improvement', description: 'Your Brutal Strike extra damage increases to 3d10.' }] },
    18: { features: [{ name: 'Indomitable Might', description: 'If your total on a Strength check or saving throw is less than your Strength score, you can use that score in place of the total.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Combat Prowess','Boon of Dimensional Travel','Boon of Energy Resistance','Boon of Fate','Boon of Fortitude','Boon of Irresistible Offense','Boon of Recovery','Boon of Skill','Boon of Speed','Boon of Undetectability'] }] },
    20: { features: [{ name: 'Primal Champion', description: 'Your Strength and Constitution scores increase by 4, and their maximum increases to 24.' }] },
  },

  // ── Bard ───────────────────────────────────────────────────────────────────
  Bard: {
    2:  { features: [{ name: 'Jack of All Trades', description: 'You can add half your proficiency bonus (rounded down) to any ability check you make that doesn\'t already use your proficiency bonus.' },
                     { name: 'Song of Rest', description: 'You can use soothing music to help revitalize your wounded allies during a short rest. If you or any friendly creatures that can hear your performance regain hit points at the end of the short rest, each gains an extra 1d6 hit points.' }] },
    3:  { features: [{ name: 'Expertise', description: 'Choose two of your proficient skills. Your proficiency bonus is doubled for any check you make using those skills.' }],
          choices: [{ type: 'subclass', label: 'Bard College', options: ['College of Dance','College of Glamour','College of Lore','College of Valor','College of Swords','College of Whispers'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Font of Inspiration', description: 'You regain all Bardic Inspiration uses when you finish a Short or Long Rest.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Bard College.' },
                     { name: 'Countercharm', description: 'You can use musical notes to disrupt mind-influencing effects. As an action, you start a performance that lasts until the end of your next turn. During that time, you and any friendly creatures within 30 feet have advantage on saving throws against being frightened or charmed.' }] },
    7:  { features: [{ name: 'Magical Secrets', description: 'You have plundered magical knowledge from a wide spectrum of disciplines. Choose two spells from any class, including this one. The spells count as Bard spells for you.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Song of Rest improvement', description: 'Your Song of Rest die increases to 1d8.' }] },
    10: { features: [{ name: 'Expertise', description: 'You can double your proficiency bonus for two more skills.' },
                     { name: 'Magical Secrets', description: 'Choose two more spells from any class.' }] },
    11: { features: [{ name: 'Song of Rest improvement', description: 'Your Song of Rest die increases to 1d10.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    13: { features: [{ name: 'Song of Rest improvement', description: 'Your Song of Rest die increases to 1d12.' }] },
    14: { features: [{ name: 'Magical Secrets', description: 'Choose two more spells from any class.' },
                     { name: 'Subclass Feature', description: 'You gain a feature from your Bard College.' }] },
    15: { features: [{ name: 'Superior Inspiration', description: 'When you roll Initiative, you regain one expended use of Bardic Inspiration.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    18: { features: [{ name: 'Magical Secrets', description: 'Choose two more spells from any class.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Luck','Boon of Fate','Boon of Skill','Boon of Spell Recall','Boon of the Night Spirit','Boon of Truesight'] }] },
    20: { features: [{ name: 'Words of Creation', description: 'You have mastered the primal words of creation. You can always have Fly and Conjure Elemental prepared, and you can cast them once each without expending a spell slot.' }] },
  },

  // ── Cleric ─────────────────────────────────────────────────────────────────
  Cleric: {
    2:  { features: [{ name: 'Channel Divinity', description: 'You gain an additional Channel Divinity option from your Divine Order (if any), and you can use it one more time per rest.' }] },
    3:  { choices: [{ type: 'subclass', label: 'Divine Domain', options: ['Life Domain','Light Domain','Trickery Domain','War Domain','Knowledge Domain','Nature Domain','Tempest Domain','Death Domain','Arcana Domain','Forge Domain','Grave Domain','Order Domain','Peace Domain'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Destroy Undead', description: 'When an undead of CR 1/2 or lower fails its saving throw against your Turn Undead, it is destroyed.' },
                     { name: 'Sear Undead', description: 'Whenever you use Turn Undead, creatures that fail the saving throw take radiant damage equal to your Wisdom modifier + your proficiency bonus.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Divine Domain.' },
                     { name: 'Channel Divinity', description: 'You can use Channel Divinity three times per rest.' }] },
    7:  { features: [{ name: 'Blessed Strikes', description: 'Choose one of the following options: Divine Strike (once per turn add 1d8 radiant or necrotic damage) or Potent Spellcasting (add Wisdom modifier to Cleric cantrip damage).' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Commune', description: 'In the past, you must have communed with your god at least once. You can cast Commune without expending a spell slot.' }] },
    10: { features: [{ name: 'Divine Intervention', description: 'You can call on your deity to intervene on your behalf. As an action, choose any Cleric spell of 5th level or lower. Your deity casts it for you once. You can use this feature again after a Long Rest.' }] },
    11: { features: [{ name: 'Destroy Undead improvement', description: 'Undead of CR 2 or lower are destroyed.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    14: { features: [{ name: 'Destroy Undead improvement', description: 'Undead of CR 3 or lower are destroyed.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    17: { features: [{ name: 'Destroy Undead improvement', description: 'Undead of CR 4 or lower are destroyed.' },
                     { name: 'Subclass Feature', description: 'You gain a feature from your Divine Domain.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Fate','Boon of Fortitude','Boon of Skill','Boon of Spell Recall','Boon of Truesight'] }] },
    20: { features: [{ name: 'Greater Divine Intervention', description: 'You can use Divine Intervention with spells of any level.' }] },
  },

  // ── Druid ──────────────────────────────────────────────────────────────────
  Druid: {
    2:  { features: [{ name: 'Wild Shape improvement', description: 'You can transform into any beast of CR 1/4 or lower that lacks a swim speed.' },
                     { name: 'Wild Companion', description: 'You can expend a use of Wild Shape to cast Find Familiar without material components.' }] },
    3:  { choices: [{ type: 'subclass', label: 'Druid Circle', options: ['Circle of the Land','Circle of the Moon','Circle of the Sea','Circle of the Stars','Circle of Wildfire','Circle of Spores'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Wild Resurgence', description: 'If you have no uses of Wild Shape remaining, you can expend a spell slot to regain one use.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Druid Circle.' },
                     { name: 'Elemental Fury', description: 'When you deal damage with a Druid cantrip or Wild Shape attack, you can add your Wisdom modifier to the damage roll.' }] },
    7:  { features: [{ name: 'Improved Wild Shape', description: 'Your Wild Shape improves based on your Druid Circle subclass.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Commune with Nature', description: 'You can cast Commune with Nature without using a spell slot.' }] },
    10: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Druid Circle.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    18: { features: [{ name: 'Beast Spells', description: 'You can cast Druid spells in any shape you assume using Wild Shape. You can perform the somatic and verbal components of a Druid spell while in a beast shape, but you can\'t provide material components.' },
                     { name: 'Timeless Body', description: 'The primal magic that you wield causes you to age more slowly. For every 10 years that pass, your body ages only 1 year.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Dimensional Travel','Boon of Energy Resistance','Boon of Fate','Boon of Skill','Boon of the Night Spirit','Boon of Truesight'] }] },
    20: { features: [{ name: 'Archdruid', description: 'The vitality of nature constantly blooms within you, giving you the following benefits: Evergreen Wild Shape (regain one use of Wild Shape when you roll Initiative), Nature Magician (you can expend Wild Shape uses to cast spells without slots), and Longevity (immune to disease, poison, and the Frightened condition).' }] },
  },

  // ── Fighter ────────────────────────────────────────────────────────────────
  Fighter: {
    2:  { features: [{ name: 'Action Surge', description: 'You can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action. Once you use this feature, you must finish a Short or Long Rest before you can use it again.' },
                     { name: 'Tactical Mind', description: 'You have a keen eye for the flow of battle. When you fail an ability check, you can expend one use of Second Wind to add 1d10 to the result, potentially turning the failure into a success.' }] },
    3:  { choices: [{ type: 'subclass', label: 'Martial Archetype', options: ['Battle Master','Champion','Eldritch Knight','Arcane Archer','Cavalier','Echo Knight','Psi Warrior','Rune Knight','Samurai'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Extra Attack', description: 'You can attack twice instead of once when you take the Attack action on your turn.' }] },
    6:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    7:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Martial Archetype.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Indomitable', description: 'You can reroll a saving throw that you fail. If you do so, you must use the new roll. You can use this feature once per long rest.' },
                     { name: 'Tactical Shift', description: 'Whenever you activate Second Wind, you can move up to half your speed without provoking opportunity attacks.' }] },
    10: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Martial Archetype.' }] },
    11: { features: [{ name: 'Extra Attack (2)', description: 'You can attack three times instead of once when you take the Attack action on your turn.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    13: { features: [{ name: 'Indomitable (2)', description: 'You can use Indomitable twice between Long Rests.' }] },
    14: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    15: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Martial Archetype.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    17: { features: [{ name: 'Action Surge (2)', description: 'You can use Action Surge twice before resting.' },
                     { name: 'Indomitable (3)', description: 'You can use Indomitable three times between Long Rests.' }] },
    18: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Martial Archetype.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Combat Prowess','Boon of Dimensional Travel','Boon of Fortitude','Boon of Irresistible Offense','Boon of Recovery','Boon of Speed'] }] },
    20: { features: [{ name: 'Extra Attack (3)', description: 'You can attack four times whenever you take the Attack action on your turn.' }] },
  },

  // ── Monk ───────────────────────────────────────────────────────────────────
  Monk: {
    2:  { features: [{ name: 'Monk\'s Focus', description: 'Your practice of martial arts gives you mastery of combat styles, uses of Ki points (equal to your Monk level), and discipline to fuel special actions.' },
                     { name: 'Unarmored Movement', description: 'Your speed increases by 10 feet while you are not wearing armor or wielding a shield. This bonus increases when you reach certain Monk levels.' },
                     { name: 'Uncanny Metabolism', description: 'When you roll Initiative, you regain all expended Ki points from your Monk\'s Focus.' }] },
    3:  { features: [{ name: 'Deflect Attacks', description: 'You can use your reaction to deflect the attack when you are hit. The damage is reduced by 1d10 + your Dexterity modifier + your Monk level.' }],
          choices: [{ type: 'subclass', label: 'Monastic Tradition', options: ['Way of the Astral Self','Way of the Drunken Master','Way of the Four Elements','Way of the Kensei','Way of the Long Death','Way of the Mercy','Way of the Open Hand','Way of the Shadow','Way of the Sun Soul'] }] },
    4:  { features: [{ name: 'Slow Fall', description: 'You can use your reaction when you fall to reduce any falling damage you take by an amount equal to five times your Monk level.' }],
          choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Extra Attack', description: 'You can attack twice instead of once when you take the Attack action on your turn.' },
                     { name: 'Stunning Strike', description: 'You can spend 1 Ki point to attempt to stun a creature you hit. The creature must succeed on a Constitution saving throw (DC = 8 + proficiency bonus + Wisdom modifier) or be Stunned until the start of your next turn.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Monastic Tradition.' },
                     { name: 'Empowered Strikes', description: 'Your Unarmed Strikes count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.' }] },
    7:  { features: [{ name: 'Evasion', description: 'Your instinctive agility lets you dodge out of the way of certain area effects, such as a blue dragon\'s lightning breath or a fireball spell. When you are subjected to an effect that allows a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw and only half damage if you fail.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Acrobatic Movement', description: 'You can move along vertical surfaces and across liquids on your turn without falling during the movement.' }] },
    10: { features: [{ name: 'Heightened Metabolism', description: 'When you use Uncanny Metabolism, you regain additional Ki points equal to your Wisdom modifier (minimum 1).' },
                     { name: 'Self-Restoration', description: 'You can use a Bonus Action to end one of the following conditions on yourself: Charmed, Frightened, or Poisoned.' }] },
    11: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Monastic Tradition.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    13: { features: [{ name: 'Deflect Energy', description: 'You can now use Deflect Attacks against spells that deal acid, cold, fire, lightning, or thunder damage.' }] },
    14: { features: [{ name: 'Disciplined Survivor', description: 'Your physical and mental discipline grant you proficiency in all saving throws.' }] },
    15: { features: [{ name: 'Perfect Focus', description: 'When you roll Initiative with no remaining Ki points from Monk\'s Focus, you regain 4 Ki points.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    18: { features: [{ name: 'Superior Defense', description: 'At the start of your turn, you can spend 3 Ki points to gain resistance to all damage types except Force damage until the start of your next turn.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Dimensional Travel','Boon of Energy Resistance','Boon of Fortitude','Boon of Irresistible Offense','Boon of Recovery','Boon of Speed','Boon of the Night Spirit'] }] },
    20: { features: [{ name: 'Body and Mind', description: 'You have mastered the ultimate techniques. Your Dexterity and Wisdom scores increase by 4, and their maximum is now 26.' }] },
  },

  // ── Paladin ────────────────────────────────────────────────────────────────
  Paladin: {
    2:  { features: [{ name: 'Divine Smite', description: 'When you hit a creature with a melee weapon, you can expend one Paladin spell slot to deal extra radiant damage (2d8 per slot level, +1d8 vs undead/fiends). No longer requires expending a slot as a reaction in 2024 rules.' },
                     { name: 'Fighting Style', description: 'You adopt a particular style of fighting as your specialty.' }],
          choices: [{ type: 'fighting_style', label: 'Fighting Style', options: ['Defense','Dueling','Great Weapon Fighting','Protection','Blind Fighting','Interception','Thrown Weapon Fighting','Two-Weapon Fighting','Unarmed Fighting'] }] },
    3:  { choices: [{ type: 'subclass', label: 'Sacred Oath', options: ['Oath of Devotion','Oath of the Ancients','Oath of Vengeance','Oath of Conquest','Oath of Glory','Oath of Redemption','Oath of the Watchers','Oathbreaker'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Extra Attack', description: 'You can attack twice instead of once when you take the Attack action on your turn.' },
                     { name: 'Faithful Steed', description: 'You can call on the aid of an otherworldly steed. You can always have Find Steed prepared, and it doesn\'t count against your prepared spells.' }] },
    6:  { features: [{ name: 'Aura of Protection', description: 'Whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the saving throw equal to your Charisma modifier (with a minimum bonus of +1), as long as you are conscious.' }] },
    7:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Sacred Oath.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Abjure Foes', description: 'As an action, you present your holy symbol and censure foes with divine power. Creatures of your choice within 60 feet that can see or hear you must succeed on a Wisdom save or be Frightened for 1 minute (concentration).' }] },
    10: { features: [{ name: 'Aura of Courage', description: 'You and friendly creatures within 10 feet of you can\'t be Frightened while you are conscious.' }] },
    11: { features: [{ name: 'Radiant Strikes', description: 'Your attacks are infused with holy power. When you hit with a melee weapon, you deal an extra 1d8 radiant damage.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    14: { features: [{ name: 'Restoring Touch', description: 'When you use Lay on Hands on a creature, you can also remove one of the following conditions: Blinded, Charmed, Deafened, Diseased, Frightened, Paralyzed, Poisoned, or Stunned.' }] },
    15: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Sacred Oath.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    18: { features: [{ name: 'Aura improvements', description: 'The range of your Aura of Protection and Aura of Courage expand to 30 feet.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Fate','Boon of Fortitude','Boon of Irresistible Offense','Boon of Recovery','Boon of Skill','Boon of Truesight'] }] },
    20: { features: [{ name: 'Sacred Oath feature', description: 'You gain a powerful capstone feature from your Sacred Oath subclass.' }] },
  },

  // ── Ranger ─────────────────────────────────────────────────────────────────
  Ranger: {
    2:  { features: [{ name: 'Fighting Style', description: 'You adopt a particular style of fighting as your specialty.' },
                     { name: 'Deft Explorer', description: 'You are a master of navigating the natural world, and you react with swift and decisive action when attacked. You gain the Roving benefit: your speed increases by 5 feet, and you can climb and swim at your normal speed.' }],
          choices: [{ type: 'fighting_style', label: 'Fighting Style', options: ['Archery','Defense','Dueling','Thrown Weapon Fighting','Two-Weapon Fighting','Blind Fighting'] }] },
    3:  { choices: [{ type: 'subclass', label: 'Ranger Conclave', options: ['Beast Master','Fey Wanderer','Gloom Stalker','Hunter','Monster Slayer','Horizon Walker','Swarmkeeper'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Extra Attack', description: 'You can attack twice instead of once when you take the Attack action on your turn.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Ranger Conclave.' },
                     { name: 'Roving', description: 'Your speed increases by 5 more feet, and you gain a climb speed and swim speed equal to your walking speed.' }] },
    7:  { features: [{ name: 'Conjure Barrage', description: 'You can cast Conjure Barrage without expending a spell slot. You can do so a number of times equal to your Wisdom modifier (minimum 1), and you regain all expended uses when you finish a Long Rest.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Tireless', description: 'Primal forces now help fuel your treks. As an Action, you can give yourself a number of Temporary Hit Points equal to 1d8 + your Wisdom modifier (minimum 1). You can use this Action a number of times equal to your Wisdom modifier (minimum once), and you regain all expended uses when you finish a Long Rest.' }] },
    10: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Ranger Conclave.' },
                     { name: 'Natures Veil', description: 'You can use a Bonus Action to magically become invisible, along with any equipment you are wearing or carrying, until the start of your next turn.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    14: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Ranger Conclave.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    17: { features: [{ name: 'Conjure Volley', description: 'You can cast Conjure Volley without expending a spell slot. You can do so once per Long Rest.' }] },
    18: { features: [{ name: 'Feral Senses', description: 'You gain preternatural senses that help you fight creatures you can\'t see. When you attack a creature you can\'t see, your inability to see it doesn\'t impose disadvantage on your attack rolls against it. You are also aware of the location of any invisible creature within 30 feet of you.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Dimensional Travel','Boon of Fate','Boon of Fortitude','Boon of Irresistible Offense','Boon of Skill','Boon of Speed','Boon of Truesight'] }] },
    20: { features: [{ name: 'Foe Slayer', description: 'You have become an unparalleled hunter of your foes. Once on each of your turns, you can add your Wisdom modifier to the attack roll or the damage roll of an attack you make against one of your favored enemies.' }] },
  },

  // ── Rogue ──────────────────────────────────────────────────────────────────
  Rogue: {
    2:  { features: [{ name: 'Cunning Action', description: 'Your quick thinking and agility allow you to move and act quickly. You can take the Dash, Disengage, or Hide action as a bonus action on each of your turns.' }] },
    3:  { features: [{ name: 'Steady Aim', description: 'As a Bonus Action, you give yourself advantage on your next attack roll on the current turn. You can use this feature only if you haven\'t moved during this turn, and after you use the Bonus Action, your speed is 0 until the end of the current turn.' }],
          choices: [{ type: 'subclass', label: 'Roguish Archetype', options: ['Arcane Trickster','Assassin','Phantom','Scout','Soulknife','Swashbuckler','Thief'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Uncanny Dodge', description: 'When an attacker that you can see hits you with an attack, you can use your reaction to halve the attack\'s damage against you.' }] },
    6:  { features: [{ name: 'Expertise', description: 'Choose two more of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make using those skills.' }] },
    7:  { features: [{ name: 'Evasion', description: 'You can nimbly dodge out of the way of certain area effects. When you are subjected to an effect that allows a Dexterity saving throw to take only half damage, you instead take no damage if you succeed.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Roguish Archetype.' }] },
    10: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    11: { features: [{ name: 'Reliable Talent', description: 'You have refined your chosen skills until they approach perfection. Whenever you make an ability check that lets you add your proficiency bonus, you can treat a d20 roll of 9 or lower as a 10.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    13: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Roguish Archetype.' }] },
    14: { features: [{ name: 'Devious Strikes', description: 'You have mastered three new ways to use your Sneak Attack: Knock Out, Obscure, and Hamstring.' }] },
    15: { features: [{ name: 'Slippery Mind', description: 'Your cunning mind is exceptionally difficult to control. You gain proficiency in Wisdom and Charisma saving throws.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    17: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Roguish Archetype.' }] },
    18: { features: [{ name: 'Elusive', description: 'You are so evasive that attackers rarely gain the upper hand against you. No attack roll has advantage against you while you aren\'t incapacitated.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Dimensional Travel','Boon of Luck','Boon of the Night Spirit','Boon of Skill','Boon of Speed','Boon of Truesight','Boon of Undetectability'] }] },
    20: { features: [{ name: 'Stroke of Luck', description: 'You have an uncanny knack for succeeding when you need to. If your attack misses a target within range, you can turn the miss into a hit. Alternatively, if you fail an ability check, you can treat the d20 roll as a 20. Once you use this feature, you can\'t use it again until you finish a Short or Long Rest.' }] },
  },

  // ── Sorcerer ───────────────────────────────────────────────────────────────
  Sorcerer: {
    2:  { features: [{ name: 'Font of Magic', description: 'You can use sorcery points to create additional spell slots or sacrifice spell slots to gain additional sorcery points. You have 2 sorcery points at level 2.' }],
          choices: [{ type: 'metamagic', label: 'Metamagic Options', options: ['Careful Spell','Distant Spell','Empowered Spell','Extended Spell','Heightened Spell','Quickened Spell','Subtle Spell','Twinned Spell','Seeking Spell','Transmuted Spell'], count: 2 }] },
    3:  { choices: [{ type: 'subclass', label: 'Sorcerous Origin', options: ['Aberrant Mind','Clockwork Soul','Draconic Bloodline','Divine Soul','Shadow Magic','Storm Sorcery','Wild Magic'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Sorcery Points increase', description: 'You now have 5 sorcery points.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Sorcerous Origin.' }] },
    7:  { features: [{ name: 'Sorcery Points increase', description: 'You now have 7 sorcery points.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    10: { choices: [{ type: 'metamagic', label: 'Metamagic Option', options: ['Careful Spell','Distant Spell','Empowered Spell','Extended Spell','Heightened Spell','Quickened Spell','Subtle Spell','Twinned Spell','Seeking Spell','Transmuted Spell'], count: 1 }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    14: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Sorcerous Origin.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    17: { choices: [{ type: 'metamagic', label: 'Metamagic Option', options: ['Careful Spell','Distant Spell','Empowered Spell','Extended Spell','Heightened Spell','Quickened Spell','Subtle Spell','Twinned Spell','Seeking Spell','Transmuted Spell'], count: 1 }] },
    18: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Sorcerous Origin.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Fate','Boon of Fortitude','Boon of Skill','Boon of Spell Recall','Boon of Truesight'] }] },
    20: { features: [{ name: 'Sorcerous Restoration', description: 'You regain 4 expended sorcery points whenever you finish a Short Rest.' }] },
  },

  // ── Warlock ────────────────────────────────────────────────────────────────
  Warlock: {
    2:  { features: [{ name: 'Magical Cunning', description: 'You can perform an esoteric rite for 1 minute. At the end of it, you regain expended Pact Magic spell slots. Once you use this feature, you must finish a Long Rest before you can do so again.' }],
          choices: [{ type: 'eldritch_invocation', label: 'Eldritch Invocation', options: ['Agonizing Blast','Armor of Shadows','Beast Speech','Beguiling Influence',"Devil's Sight",'Eldritch Mind','Gaze of Two Minds','Mask of Many Faces','Misty Visions','One with Shadows','Repelling Blast','Thief of Five Fates'], count: 1 }] },
    3:  { choices: [{ type: 'subclass', label: 'Otherworldly Patron', options: ['The Archfey','The Celestial','The Fiend','The Great Old One','The Hexblade','The Undead','The Undying'] },
                    { type: 'eldritch_invocation', label: 'Eldritch Invocation', options: ['Agonizing Blast','Armor of Shadows','Beast Speech','Beguiling Influence',"Devil's Sight",'Eldritch Mind','Gaze of Two Minds','Mask of Many Faces','Misty Visions','One with Shadows','Repelling Blast','Thief of Five Fates'], count: 1 }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] },
                    { type: 'eldritch_invocation', label: 'Eldritch Invocation', options: ['Agonizing Blast','Armor of Shadows','Beast Speech','Beguiling Influence',"Devil's Sight",'Eldritch Mind','Gaze of Two Minds','Mask of Many Faces','Misty Visions','One with Shadows','Repelling Blast','Thief of Five Fates'], count: 1 }] },
    5:  { features: [{ name: 'Thirsting Blade', description: 'If you have the Pact of the Blade invocation, you can attack twice, instead of once, with your pact weapon.' }],
          choices: [{ type: 'eldritch_invocation', label: 'Eldritch Invocation', options: ['Agonizing Blast','Armor of Shadows','Beast Speech','Beguiling Influence',"Devil's Sight",'Eldritch Mind','Gaze of Two Minds','Mask of Many Faces','Misty Visions','One with Shadows','Repelling Blast','Thief of Five Fates'], count: 1 }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Otherworldly Patron.' }] },
    7:  { choices: [{ type: 'eldritch_invocation', label: 'Eldritch Invocation', options: ['Agonizing Blast','Armor of Shadows','Beast Speech','Beguiling Influence',"Devil's Sight",'Eldritch Mind','Gaze of Two Minds','Mask of Many Faces','Misty Visions','One with Shadows','Repelling Blast','Thief of Five Fates'], count: 1 }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { choices: [{ type: 'eldritch_invocation', label: 'Eldritch Invocation', options: ['Agonizing Blast','Armor of Shadows','Beast Speech','Beguiling Influence',"Devil's Sight",'Eldritch Mind','Gaze of Two Minds','Mask of Many Faces','Misty Visions','One with Shadows','Repelling Blast','Thief of Five Fates'], count: 1 }] },
    10: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Otherworldly Patron.' }] },
    11: { features: [{ name: 'Mystic Arcanum (6th)', description: 'Your patron bestows upon you a magical secret called an Arcanum. Choose one 6th-level spell from the Warlock spell list as this arcanum. You can cast it once without expending a spell slot.' }],
          choices: [{ type: 'eldritch_invocation', label: 'Eldritch Invocation', options: ['Agonizing Blast','Armor of Shadows','Beast Speech','Beguiling Influence',"Devil's Sight",'Eldritch Mind','Gaze of Two Minds','Mask of Many Faces','Misty Visions','One with Shadows','Repelling Blast','Thief of Five Fates'], count: 1 }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    13: { features: [{ name: 'Mystic Arcanum (7th)', description: 'You gain a 7th-level Arcanum spell.' }] },
    15: { features: [{ name: 'Mystic Arcanum (8th)', description: 'You gain an 8th-level Arcanum spell.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    17: { features: [{ name: 'Mystic Arcanum (9th)', description: 'You gain a 9th-level Arcanum spell.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Fate','Boon of Fortitude','Boon of Skill','Boon of Spell Recall','Boon of Truesight','Boon of the Night Spirit'] }] },
    20: { features: [{ name: 'Eldritch Master', description: 'You can spend 1 minute entreating your patron for aid to regain all your expended Pact Magic spell slots. Once you use this feature, you can\'t use it again until you finish a Long Rest.' }] },
  },

  // ── Wizard ─────────────────────────────────────────────────────────────────
  Wizard: {
    2:  { features: [{ name: 'Scholar', description: 'While studying magic, you also specialized in another field of study. Choose one of the following skills in which you have proficiency: Arcana, History, Investigation, Medicine, Nature, or Religion. You have Expertise in the chosen skill.' }] },
    3:  { choices: [{ type: 'subclass', label: 'Arcane Tradition', options: ['School of Abjuration','School of Conjuration','School of Divination','School of Enchantment','School of Evocation','School of Illusion','School of Necromancy','School of Transmutation','Order of Scribes','Bladesinging','Chronurgy Magic','Graviturgy Magic','War Magic'] }] },
    4:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    5:  { features: [{ name: 'Memorize Spell', description: 'Whenever you finish a Short Rest, you can study your spellbook and replace one of the 1st-level or higher Wizard spells you have prepared for your Wizard level with another Wizard spell from your spellbook.' }] },
    6:  { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Arcane Tradition.' }] },
    7:  { features: [{ name: 'Spellbook improvement', description: 'Add two Wizard spells of your choice to your spellbook.' }] },
    8:  { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    9:  { features: [{ name: 'Spellbook improvement', description: 'Add two more Wizard spells to your spellbook.' }] },
    10: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Arcane Tradition.' }] },
    12: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    14: { features: [{ name: 'Subclass Feature', description: 'You gain a feature from your Arcane Tradition.' }] },
    16: { choices: [{ type: 'asi', label: 'Ability Score Improvement', options: [] }] },
    18: { features: [{ name: 'Spell Mastery', description: 'You have achieved such mastery over certain spells that you can cast them at will. Choose a 1st-level and a 2nd-level Wizard spell in your spellbook. You can cast those spells at their lowest level without expending a spell slot.' }] },
    19: { choices: [{ type: 'epic_boon', label: 'Epic Boon', options: ['Boon of Fate','Boon of Fortitude','Boon of Skill','Boon of Spell Recall','Boon of Truesight'] }] },
    20: { features: [{ name: 'Signature Spells', description: 'You gain mastery over two powerful spells and can cast them with little effort. Choose two 3rd-level Wizard spells in your spellbook as your signature spells. You always have these spells prepared, and you can cast each of them once at 3rd level without expending a spell slot.' }] },
  },
}
